### ISSUE TITLE
templates/log_list.html.eex:15: function full_path/1 undefined

### ISSUE THREAD

**Issue by JoelPM** [awetzel/ewebmachine#15]
Apologies if this ends up being a dumb user error on my part, but when using ewebmachine as a dependency and attempting to compile, I get the following error:

```bash
$ mix deps.compile ewebmachine
==> ewebmachine
Compiled lib/ewebmachine.ex
lib/conn_logger.ex:43: warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
Compiled lib/conn_logger.ex
Compiled lib/builders.ex
Compiled lib/handlers.ex

== Compilation error on file lib/plugs.ex ==
** (CompileError) templates/log_list.html.eex:15: function full_path/1 undefined
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:122: :erl_eval.exprs/5
```

mix.exs deps for reference:
```elixir
  defp deps do
    [
      {:ewebmachine, "2.0.8"},
      {:cowboy,      "1.0.2"}
    ]
  end
```

When I clone the ewebmachine repo locally and build it there are no errors, so I'm not sure what my problem is.

Elixir 1.0.5 and erlang 18.0.2.

Thanks,
Joel

**Comment by awetzel** [comment]
Hello Joel, thanks for the report, seems to be a api change of plug. It works on clone because in this case you work with the mix.lock and the exact working plug version. 

I will update to last plug version and fix `deps` constraint next week.

**Comment by JoelPM** [comment]
Hi Arnaud, I submitted a PR that I believe addresses the incompatibilities and also fixes the deprecated erlang.now call. Feel free to reject if it's not fixed the way you'd like. Thanks for making ewebmachine!

**Comment by awetzel** [comment]
I thinks it is ok now, thanks a lot for the PR and report !
