### ISSUE TITLE
/wm_debug url broken

### ISSUE THREAD

**Issue by jeanparpaillon** [awetzel/ewebmachine#27]
/wm_debug url is broken

**Comment by jeanparpaillon** [comment]
When retrieveing list of logs, url add a superfluous /wm_debug ->
/wm_debug/wm_debug/log/:id

**Comment by awetzel** [comment]
maybe linked to https://github.com/awetzel/ewebmachine/pull/10 ?

**Comment by jeanparpaillon** [comment]
Problem was linked to macro re-writing
