### ISSUE TITLE
Need more elixir-specific examples

### ISSUE THREAD

**Issue by nickretallack** [awetzel/ewebmachine#9]
I wrote a simple resource:

```
	resource ['test'] do
		allowed_methods do
			['GET']
		end

		to_html do
			"Hello"
		end
	end
```

When I try to GET it, this happens:

```
[{erlang,atom_to_list,["GET"],[]},
 {webmachine_decision_core,'-decision/1-lc$^0/1-0-',1,
                           [{file,"src/webmachine_decision_core.erl"},
                            {line,178}]},
 {webmachine_decision_core,decision,1,
                           [{file,"src/webmachine_decision_core.erl"},
                            {line,178}]},
 {webmachine_decision_core,handle_request,2,
                           [{file,"src/webmachine_decision_core.erl"},
                            {line,33}]},
 {webmachine_mochiweb,loop,2,[{file,"src/webmachine_mochiweb.erl"},{line,74}]},
 {mochiweb_http,parse_headers,5,[{file,"src/mochiweb_http.erl"},{line,180}]},
 {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]
```

Oh, I get it.  It needs to be an atom, not a list-string like it is in the erlang version.

It'd be neat if you could provide a simple example of how to do CRUD in ewebmachine.  Guessing the differences from the erlang version is kind of hard.  Especially when the error messages are like this.

Would it be possible to add more informative errors?  Or would it be on erlang webmachine to do that?

**Comment by awetzel** [comment]
Ewebmachine is now a full Elixir implementation of webmachine with only `Plug` as dependency, with a dedicated documentation here http://hexdocs.pm/ewebmachine/ .
To use the old webmachine wrapper, use the "1.0-legacy" branch.
